@echo off
rd "default\Cookies"
rd "default\Local Settings"
rd "default\My Documents"
rd "default\NetHood"
rd "default\PrintHood"
rd "default\Recent"
rd "default\Templates"
rd "default\SendTo"
rd "default\Start Menu"
rd "default\Application Data"
rd "default\AppData\Local\history"
rd "default\AppData\Local\Temporary Internet Files"
rd "default\AppData\Local\Application Data"
